### ISSUE TITLE
shooting for too long causes massive lag

### ISSUE THREAD

**Issue by s4ntolmo** [uran247/voxel-planes-datapack#17]
i've been trying the datapack and i've been shooting stuff around with the planes' guns. after some time, a massive lag spike appears and it doesn't stop. the only way to make it stop is to run /kill @e. I believe it is because of the bullets calculating an undefined trajectory. what kind of entity are they and how can I get rid of them without killing all the other mobs?

**Comment by uran247** [comment]
I'm using marker for calculating a trajectory.
It seems to occur due to entities are immediately unloaded when they go to an unloaded chunk from 1.17.
When those entities loaded again, they causes lag spikes.
I'm planning to add a method that cleans those entities in v0.5.0.
