### ISSUE TITLE
The plane deletes items in the offhand and slot 9

### ISSUE THREAD

**Issue by pityipalko** [uran247/voxel-planes-datapack#18]
When going into the plane, it deletes all armor, item in offhand and item in slot 9 (lock turning)
1.18.1 on fabric server
also it works very well with friends on survival server 😄

**Comment by uran247** [comment]
It is due to change of a syntax of lootable from 1.18.
It will be fixed in v0.5.0 and officially compatible with 1.18.

**Comment by pityipalko** [comment]
Thanks for fast reply! I also have a question pertaining to the estimated release of v0.5.0.
