### ISSUE TITLE
resource reload failed/リソースのリロードに失敗しました

### ISSUE THREAD

**Issue by NewChunks** [uran247/voxel-planes-datapack#6]
english: hello! I am a huge fan of your pack and I wanted to use it on a server with my friends. they downloaded the datapack and everything fine but when one of my friends loads the resource pack it just says "resource reload failed" I looked online and couldn't find anything that helped him. I was wondering if you could help.

日本語（グーグル翻訳）
こんにちは！ 私はあなたのパックの大ファンで、友達と一緒にサーバーで使いたいと思っていました。 彼らはデータパックとすべてを正常にダウンロードしましたが、友人の1人がリソースパックをロードすると、「リソースの再読み込みに失敗しました」と表示されます。オンラインで調べたところ、彼に役立つものは見つかりませんでした。 手伝ってくれないかと思っていました。

**Comment by uran247** [comment]
This resource pack needs sufficient video memory.
If your friend doesn't use a graphic card or only have few video memory, it may cause fail to load the resourcepack.

**Comment by uran247** [comment]
Rleased low resolution resourcepack as a measure for "resource reload failed".
