### ISSUE TITLE
p-38l not in wiki/whats the recipe for the p-38l?  ///  ウィキにないp-38l / p-38lのレシピは？

### ISSUE THREAD

**Issue by NewChunks** [uran247/voxel-planes-datapack#7]
English: I can't find the p-38l in the wiki and can't figure out how to craft it.

日本語:(グーグル翻訳）
ウィキでp-38lを見つけることができず、それを作成する方法を理解できません。

**Comment by uran247** [comment]
P-38L is in development. This plane doesn't have a recipe ,flight model and weapons.
Please wait official release.
